<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="Rohit" failures="1" tests="3" name="Error Validation Test" time="21.949" errors="0" timestamp="2023-12-31T18:30:33 IST">
  <testcase classname="SeleniumFrameworkPOM.Test.ErrorValidation" name="LoginErrorValidation" time="0.928"/>
  <testcase classname="SeleniumFrameworkPOM.Test.ErrorValidation" name="productErrorValidation" time="3.04">
    <skipped/>
  </testcase> <!-- productErrorValidation -->
  <testcase classname="SeleniumFrameworkPOM.Test.ErrorValidation" name="productErrorValidation" time="3.034">
    <failure type="java.lang.AssertionError" message="expected [false] but found [true]">
      <![CDATA[java.lang.AssertionError: expected [false] but found [true]
at SeleniumFrameworkPOM.Test.ErrorValidation.productErrorValidation(ErrorValidation.java:52)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1541)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
at java.base/java.lang.Thread.run(Thread.java:834)
... Removed 21 stack frames]]>
    </failure>
  </testcase> <!-- productErrorValidation -->
</testsuite> <!-- Error Validation Test -->
